apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec: 
      containers:
        - name: product
          image: ebazdev/product:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              value: 'mongodb://ebaz-prod:774CPXo65J8i@103.229.178.56:27017/ebaz-prod?directConnection=true'
            - name: JWT_KEY
              value: '279112db517a6fadbfbb53500ee5e142a9036f1c972739e895c0d3ff7aa84af3'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ebazaar_prod'
            - name: NATS_USER
              value: 'nats_prod'
            - name: NATS_PASS
              value: 'NaTs@Prod$EBaz'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'production'
            - name: COLA_USERNAME
              value: 'bazaar'
            - name: COLA_PASSWORD
              value: 'M8@46jkljkjkljlk#$2024'
            - name: COLA_GET_TOKEN_URI
              value: 'http://122.201.28.22:8083/api/tokenbazaar'
            - name: COLA_PRODUCTS_BY_MERCHANTID
              value: 'http://122.201.28.22:8083/api/ebazaar/productremains'
            - name: TOTAL_CUSTOMER_ID
              value: "66f12d655e36613db5743430"
            - name: COLA_CUSTOMER_ID
              value: "66ebe3e3c0acbbab7824b195"
          readinessProbe:
            httpGet:
              path: /api/v1/product/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/product/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000