apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec: 
      containers:
        - name: customer
          image: tsendebna/customer:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://ebaz-dev:774CPXo65J8i@103.229.178.56:27017/ebaz-dev?directConnection=true'
            - name: JWT_KEY
              value: '279112db517a6fadbfbb53500ee5e142a9036f1c972739e895c0d3ff7aa84af3'
            - name: NATS_URL
              value: 'http://114.129.42.59:4222'
            - name: NATS_CLUSTER_ID
              value: 'ebazaar_dev'
            - name: NATS_USER
              value: 'nats_dev'
            - name: NATS_PASS
              value: 'NaTs@Dev$EBaz'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'development'
          readinessProbe:
            httpGet:
              path: /api/v1/customer/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/customer/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: customer-srv
spec:
  selector:
    app: customer
  ports:
    - name: customer
      protocol: TCP
      port: 3000
      targetPort: 3000