name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "SHA of version to promote from dev"
        required: true

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.get-services.outputs.services }}
    permissions:
      contents: read
      actions: read
    steps:
      - name: Debug Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "SHA: ${{ inputs.version }}"

      - id: get-services
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // Get repository name from full repository path
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              
              console.log('Repository context:', {
                owner: owner,
                repo: repo,
                sha: '${{ inputs.version }}'
              });

              // Initialize empty array for services
              let deployedServices = [];

              // First check if the commit exists
              const { data: commit } = await github.rest.repos.getCommit({
                owner: owner,
                repo: repo,
                ref: '${{ inputs.version }}'
              });
              
              console.log('Checking commit:', commit.sha);
              
              // Then get workflow runs
              const { data: workflows } = await github.rest.actions.listRepoWorkflows({
                owner: owner,
                repo: repo
              });
              
              console.log('Available workflows:', workflows.workflows.map(w => w.path));
              
              const devWorkflow = workflows.workflows.find(w => w.path === '.github/workflows/dev-deploy.yml');
              if (!devWorkflow) {
                console.log('dev-deploy.yml workflow not found');
                core.setOutput('services', '[]');
                return;
              }
              
              const workflow_runs = await github.rest.actions.listWorkflowRuns({
                owner: owner,
                repo: repo,
                workflow_id: devWorkflow.id,
                sha: '${{ inputs.version }}'
              });
              
              console.log('Found workflow runs:', workflow_runs.data);
              
              const run = workflow_runs.data.workflow_runs[0];
              if (!run) {
                console.log('No dev deployment found for this SHA');
                core.setOutput('services', '[]');
                return;
              }

              console.log('Using workflow run:', run.id);
              
              const jobs = await github.rest.actions.listJobsForWorkflowRun({
                owner: owner,
                repo: repo,
                run_id: run.id
              });
              
              console.log('All jobs:', jobs.data.jobs.map(j => ({
                name: j.name,
                status: j.status,
                conclusion: j.conclusion
              })));
              
              deployedServices = jobs.data.jobs
                .filter(job => job.name.includes('build-and-deploy'))
                .map(job => {
                  console.log('Processing job name:', job.name);
                  // More aggressive cleanup and matching
                  const cleanName = job.name.replace(/[\n\r\s]+/g, ' ').trim();
                  console.log('Cleaned job name:', cleanName);
                  const match = cleanName.match(/build-and-deploy \(([^)]+)\)/);
                  console.log('Match result:', match);
                  return match ? match[1].trim() : null;
                })
                .filter(Boolean);
              
              console.log('Raw job names:', jobs.data.jobs.map(j => j.name));
              console.log('After filter:', jobs.data.jobs.filter(job => job.name.includes('build-and-deploy')).map(j => j.name));
              console.log('Final detected services:', deployedServices);
              
              if (deployedServices.length === 0) {
                console.log('No build-and-deploy jobs found in the workflow run');
                // List all job names to help debug
                console.log('Available job names:', jobs.data.jobs.map(j => j.name));
              }
              
              core.setOutput('services', JSON.stringify(deployedServices));
            } catch (error) {
              console.error('Error:', error);
              core.setOutput('services', '[]');
              core.setFailed(error.message);
            }

  deploy:
    needs: detect-services
    if: fromJson(needs.detect-services.outputs.services) != '[]'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      deployments: write
      issues: write
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-services.outputs.services) }}

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Kubernetes Prod
        run: |
          SERVICE=$(echo "${{ matrix.service }}" | tr -d '\n\r')

          kubectl config set-cluster kubernetes --server=${{ secrets.K8S_SERVER_PROD }}
          kubectl config set clusters.kubernetes.certificate-authority-data ${{ secrets.K8S_CERT_PROD }}
          kubectl config set-credentials kubernetes-admin --token=${{ secrets.K8S_TOKEN_PROD }}
          kubectl config set-context kubernetes-admin@kubernetes --cluster=kubernetes --user=kubernetes-admin
          kubectl config use-context kubernetes-admin@kubernetes

          kubectl apply -f ./${SERVICE}/k8s/prod/auth-depl.yaml
          kubectl set image deployment/${SERVICE}-depl ${SERVICE}=${{ secrets.DOCKER_USERNAME }}/${SERVICE}:${{ inputs.version }}
          kubectl rollout status deployment/${SERVICE}-depl

      - name: Verify Deployment
        run: |
          SERVICE=$(echo "${{ matrix.service }}" | tr -d '\n\r')
          kubectl get pods | grep ${SERVICE}
          kubectl get service ${SERVICE}-srv

      - name: Verify Dev Deployment Status
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const service = '${{ matrix.service }}';
              const { data: deployments } = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.name,
                workflow_id: 'dev-deploy.yml',
                status: 'completed',
                conclusion: 'success',
                branch: 'main'
              });

              const devDeployment = deployments.workflow_runs.find(run => 
                run.head_sha === '${{ inputs.version }}'
              );

              if (!devDeployment) {
                core.setFailed(`Service ${service} was not successfully deployed to dev`);
              }
            } catch (error) {
              console.error('Error checking deployment:', error);
              core.setFailed(error.message);
            }

      - name: Create Production Deployment
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.createDeployment({
                owner: context.repo.owner,
                repo: context.repo.name,
                ref: '${{ inputs.version }}',
                environment: 'production',
                task: '${{ matrix.service }}',
                auto_merge: false
              });
            } catch (error) {
              console.error('Error creating deployment:', error);
              core.setFailed(error.message);
            }

      - name: Store Rollback Info
        run: |
          SERVICE=${{ matrix.service }}
          PREV_VERSION=$(kubectl get deployment/${SERVICE}-depl -o=jsonpath='{$.spec.template.spec.containers[0].image}')
          echo "Previous version was: $PREV_VERSION"
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

      - name: Notify Deployment Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const status = '${{ job.status }}';
              const service = '${{ matrix.service }}';
              const version = '${{ inputs.version }}';
              
              if (context.eventName === 'workflow_dispatch') {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.name,
                  issue_number: context.payload.inputs.issue_number || context.runId,
                  body: `Production deployment of ${service} ${status} for version ${version}`
                });
              }
            } catch (error) {
              console.error('Error creating comment:', error);
              console.log('Failed to create comment:', error.message);
            }
