name: Pull Request Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!.github/**"

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      services: ${{ steps.changes.outputs.services }}
      has_changes: ${{ steps.check-services.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changes
        run: |
          SERVICES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep "^[^/]*/" | \
            grep -v "^core/" | \
            grep -v "^.github/" | \
            cut -d/ -f1 | \
            sort -u || true)
          if [ -z "$SERVICES" ]; then
            echo "services=[]" >> $GITHUB_OUTPUT
          else
            echo "services=$(echo "$SERVICES" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          fi

      - id: check-services
        run: |
          SERVICES='${{ steps.changes.outputs.services }}'
          if [ "$SERVICES" = "[]" ] || [ -z "$(echo $SERVICES | jq '. | length')" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

  pull-request-check:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    name: PR Check - ${{ matrix.service }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Setup Core
        run: |
          cd core
          npm ci
          npm run build
          npm link

      - name: Install Service Dependencies
        run: |
          cd ${{ matrix.service }}
          npm link @ezdev/core
          npm ci

      - name: Run Lint
        run: |
          cd ${{ matrix.service }}
          npm run lint

      - name: Run Tests
        env:
          JWT_KEY: test_jwt_key
          NODE_ENV: test
        run: |
          cd ${{ matrix.service }}
          npm run test:ci
