name: Pull Request Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!.github/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.changes.outputs.services }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changes
        run: |
          SERVICES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep "^[^/]*/" | \
            grep -v "^core/" | \
            grep -v "^.github/" | \
            cut -d/ -f1 | \
            sort -u | \
            xargs)
          echo "services=$(echo "$SERVICES" | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  pull-request-check:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    name: PR Check - ${{ matrix.service }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Core
        run: |
          cd core
          npm install
          npm run build
          npm link

      - name: Install Service Dependencies
        run: |
          cd ${{ matrix.service }}
          npm link @ezdev/core
          npm install

      - name: Run Tests
        run: |
          cd ${{ matrix.service }}
          npm test
